New CLI for ci
alercebroker/pipeline pull request #277
Opened 2023-11-17 12:19 UTC by AlxEnashi

## Summary of the changes

The functionality is the same, te idea is to make it mor readable, add documentation and make it user friendly.

## Observations

 - [ ] Error management (ej: buffer file corruped -> please run prepare)
 - [ ] Final names for commands.
 - [ ] The documentation.

## About this PR:

- [ ] You added the necessary documentation for the team to understand your work.
- [ ] You linked this PR to the corresponding issue or user story.
- [ ] Your changes fulfill the Definition of Done of the issue or user story.
- [ ] Your changes were tested with manual testing before being submitted.
- [ ] Your changes were tested with automatic unit tests.
- [ ] Your changes were tested with automatic integration tests.

2023-11-20 13:14 UTC, dirodriguezm requested changes

2023-11-20 13:14 UTC, dirodriguezm commented on .github/workflows/staging_ci.yaml
> +          poetry run python new_main.py update update-version \
Creo que es mala práctica ponerle new a las cosas. Más que nada porque en el momento que haga merge deja de ser new. Por qué no se puede reemplazar el main con la funcionalidad nueva ?

2023-11-20 14:41 UTC, AlxEnashi commented on .github/workflows/staging_ci.yaml
> +          poetry run python new_main.py update update-version \
Se puede y la idea era eliminar el anterior, no lo habia hecho para poder seguir leyendolo y se me olvido sacar el "new_". Lo cambio en el proximo commit...

2023-11-21 12:25 UTC, dirodriguezm approved these changes

2023-11-21 12:25 UTC, merged