Ztf classifier can predict
alercebroker/pipeline pull request #336
Opened 2023-12-22 12:21 UTC by AlxEnashi

## Summary of the changes

Add a can predict method to the ZTF classifier in lc classifier.
It can predict if:
 - There are all the features
 -  At least 1 alert is from ztf

## Observations

This change is for archiving and completness, the changes that affect pipeline are in the lc_classifier repo.

## About this PR:

- [ ] You added the necessary documentation for the team to understand your work.
- [ ] You linked this PR to the corresponding issue or user story.
- [ ] Your changes fulfill the Definition of Done of the issue or user story.
- [ ] Your changes were tested with manual testing before being submitted.
- [ ] Your changes were tested with automatic unit tests.
- [ ] Your changes were tested with automatic integration tests.

2023-12-22 15:07 UTC, AlxEnashi commented
Problema, por como se hace el checkeo en dataframe el step es sensible a si ztf esta en mayusculas o minusculas. no estoy seguro como hacer ese check en pandas de una mejor manera.

2024-01-02 15:11 UTC, dirodriguezm requested changes

2024-01-02 15:11 UTC, dirodriguezm commented on libs/lc_classifier/lc_classifier/classifier/models.py
> +        return True
Creo que este debería lanzar NotImplemented para asegurar que las clases concretas realizan ese check y evitar errores en el futuro.

2024-01-02 15:11 UTC, dirodriguezm commented on libs/lc_classifier/lc_classifier/classifier/models.py
> +            detections_ok = (data.detections["tid"] == "ztf").any()
Qué pasa con las que no son de ZTF ? Si asumimos que en este punto todas las detecciones son de ZTF, debería decir `.all()`. Si no, entonces debería hacerse un filtro y de todas formas usar `.all()` ya que si alguna detección no fuera de ZTF, el clasificador no debería clasificarla.

2024-01-22 12:09 UTC, closed without merging