Refactor/key oid candid alerts
alercebroker/pipeline pull request #378
Opened 2024-01-12 15:20 UTC by AlxEnashi

## Summary of the changes

Changed al uses of drop duplicates in detections and non detections dataframes by candid to by candid and oid.
Changed criteria for non detections insert in correctino step.

## Observations

<-- Add some notes to keep in mind !-->

#### Components that need updates and steps to follow

Pull from the changes to scribe and db. 
https://github.com/alercebroker/pipeline/pull/377

## About this PR:

- [ ] You added the necessary documentation for the team to understand your work.
- [ ] You linked this PR to the corresponding issue or user story.
- [ ] Your changes fulfill the Definition of Done of the issue or user story.
- [ ] Your changes were tested with manual testing before being submitted.
- [ ] Your changes were tested with automatic unit tests.
- [ ] Your changes were tested with automatic integration tests.

2024-01-12 16:10 UTC, dirodriguezm requested changes

2024-01-12 16:10 UTC, dirodriguezm commented on correction_step/correction/core/corrector.py
> +        extras = extras.reset_index(names=["candid"]).drop_duplicates(["candid", "oid"]).set_index("candid")
Esto es problemático, porque al setear index candid como ya no es único, si yo hago `df.loc[some_candid]`, va a retornar más de un elemento y romper el resto de la ejecución

2024-01-12 18:01 UTC, AlxEnashi commented on correction_step/correction/core/corrector.py
> +        extras = extras.reset_index(names=["candid"]).drop_duplicates(["candid", "oid"]).set_index("candid")
ese extra son los extra fields? esos si deberian ser uno por candid no?

2024-01-12 18:13 UTC, dirodriguezm commented on correction_step/correction/core/corrector.py
> +        extras = extras.reset_index(names=["candid"]).drop_duplicates(["candid", "oid"]).set_index("candid")
No solo para los extra fields. Cuando tienes una lista de detecciones con indice candid y usas `loc`, eventualmente puede retornar más de un valor

2024-01-12 18:14 UTC, dirodriguezm commented on correction_step/correction/core/corrector.py
> +        extras = extras.reset_index(names=["candid"]).drop_duplicates(["candid", "oid"]).set_index("candid")
Lo que se me ocurre es hacer index por oid,candid pero desconozco el funcionamiento de loc con multiindex

2024-01-17 18:19 UTC, dirodriguezm commented
Will merge this and the feature step will be fixed on a follow up PR

2024-01-17 18:20 UTC, dirodriguezm approved these changes

2024-01-17 18:20 UTC, merged